In [1]:
"""=============================================================================
Ex1: DECOMPOSITION
    Câu 3: QA Decomposition
        a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
        b) Phân tích thành các thành phần Q và R. In kết quả
        c) Tái tạo lại ma trận A từ các thành phần Q và R
============================================================================="""
    
import numpy  as np
import random       
from scipy.linalg import qr

##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end)
            
            # Thêm giá trị vào dòng hiện hành 
            row.append(a)
            
        # Thêm dòng vào ma trận    
        mtr.append(row)
        
    return np.array(mtr)
##------------------------------------------------------------------------------

## a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
m, n, min, max = 4, 4, 5, 10
A = create_matrix_random(m, n, min, max)
print('Ma trận A', A.shape, ':\n', A)

## b) Phân tích thành các thành phần Q và R. In kết quả
print('\n*** Áp dụng phân rã QR:')
Q, R = qr(A)

print('Ma trận Q', Q.shape, ':\n', Q)
print('Ma trận R', R.shape, ':\n', R)

## c) Tái tạo lại ma trận A từ các thành phần Q và R
print('\nTái tạo A từ Q, R (kiểm chứng lại phép phân rã):\n', Q.dot(R))

Ma trận A (4, 4) :
 [[10  8 10  8]
 [11  7  9 11]
 [ 9  9  6  8]
 [ 7 10  7 11]]

*** Áp dụng phân rã QR:
Ma trận Q (4, 4) :
 [[-0.53376051 -0.15907167  0.59696657 -0.57743124]
 [-0.58713656 -0.54446958 -0.09852989  0.59085987]
 [-0.48038446  0.22632624 -0.75022984 -0.39390658]
 [-0.37363236  0.79184942  0.26660452  0.402859  ]]
Ma trận R (4, 4) :
 [[-18.734994   -16.43982379 -16.11956748 -18.68161794]
 [  0.           4.87156995   0.40996045   3.2592148 ]
 [  0.           0.           2.44774929   0.6227148 ]
 [  0.           0.           0.           3.16020508]]

Tái tạo A từ Q, R (kiểm chứng lại phép phân rã):
 [[10.  8. 10.  8.]
 [11.  7.  9. 11.]
 [ 9.  9.  6.  8.]
 [ 7. 10.  7. 11.]]


In [28]:
"""=============================================================================
Ex1: DECOMPOSITION
    Câu 4: Cholesky Decomposition
        a) Tạo ma trận A(3 x 3) chứa các giá trị ngẫu nhiên trong khoảng 3 - 9
        b) Chuyển A thành ma trận vuông đối xứng theo tam giác dưới
        c) Thực hiện phân rã Cholesky, nếu có thể
============================================================================="""

import numpy  as np
import random       
from numpy.linalg import cholesky
## numpy.linalg.cholesky: Default --> LOWER
## scipy.linalg.cholesky: Default --> UPPER

##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end)
            
            # Thêm giá trị vào dòng hiện hành 
            row.append(a)
            
        # Thêm dòng vào ma trận    
        mtr.append(row)
        
    return np.array(mtr)
##------------------------------------------------------------------------------

## a) Tạo ma trận A(3 x 3) chứa các giá trị ngẫu nhiên trong khoảng 3 - 9
m, n, min, max = 3, 3, 3, 9
A = create_matrix_random(m, n, min, max)

## b) Chuyển A thành ma trận vuông đối xứng theo tam giác dưới
## Điều kiện phân rã Cholesky: ma trận ĐỐI XỨNG
for i in range(A.shape[0]):
    for j in range(i):
        A[j][i] = A[i][j]
print('*** Ma trận A', A.shape, ':\n', A)        

## c) Thực hiện phân rã Cholesky, nếu có thể
## Kiểm tra ma trận xác định dương
test = np.linalg.eigvalsh(A)

pos_def = np.all(test > 0)   
if (pos_def == True):
    L = cholesky(A)

    print('Ma trận L', L.shape, ':\n', L)

    print('Tái tạo ma trận A:\n', L.dot(L.T))
else:
    print('\nMa trận A KHÔNG thỏa điều kiện XÁC ĐỊNH DƯƠNG')
    
##------------------------------------------------------------------------------
## Hàm tạo ma trận xác định dương    
##------------------------------------------------------------------------------
def create_matrix_positive_definite(m, n, start, end):
    A       = None
    pos_def = False
    
    while (pos_def == False):
        A = create_matrix_random(m, n, start, end)
        for i in range(A.shape[0]):
            for j in range(i):
                A[j][i] = A[i][j]
        test    = np.linalg.eigvalsh(A)
        pos_def = np.all(test > 0)
    return A
##------------------------------------------------------------------------------
A = create_matrix_positive_definite(3, 3, 3, 9)
print('\n*** Ma trận A', A.shape, 'thỏa điều kiện XÁC ĐỊNH DƯƠNG:\n', A)

print('Áp dụng phân rã Cholesky:')
L = cholesky(A)
print('Ma trận L', L.shape, ':\n', L)

print('\nTái tạo A từ L, L_T (kiểm chứng lại phép phân rã)\n', L.dot(L.T))

*** Ma trận A (3, 3) :
 [[9 4 4]
 [4 8 9]
 [4 9 5]]

Ma trận A KHÔNG thỏa điều kiện XÁC ĐỊNH DƯƠNG

*** Ma trận A (3, 3) thỏa điều kiện XÁC ĐỊNH DƯƠNG:
 [[8 5 5]
 [5 9 6]
 [5 6 6]]
Áp dụng phân rã Cholesky:
Ma trận L (3, 3) :
 [[2.82842712 0.         0.        ]
 [1.76776695 2.42383993 0.        ]
 [1.76776695 1.18613443 1.21164562]]

Tái tạo A từ L, L_T (kiểm chứng lại phép phân rã)
 [[8. 5. 5.]
 [5. 9. 6.]
 [5. 6. 6.]]


In [2]:
"""=============================================================================
Ex1: DECOMPOSITION
    Câu 1: LU Decomposition
        a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
        b) Phân tích thành các thành phần P, L, U. In kết quả
        c) Tái tạo lại ma trận A từ các thành phần P, L, U
============================================================================="""
    
import numpy  as np
import random       
from scipy.linalg import lu

##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end)
            
            # Thêm giá trị vào dòng hiện hành 
            row.append(a)
            
        # Thêm dòng vào ma trận    
        mtr.append(row)
        
    return np.array(mtr)
##------------------------------------------------------------------------------

## a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
## Ma trận HÌNH CHỮ NHẬT: A(m, n) = P_T(m, m).L(m, n).U(n, n)
m, n, min, max = 4, 4, 1, 10
A = create_matrix_random(m, n, min, max)
print('Ma trận VUÔNG A', A.shape, ':\n', A)

## b) Phân tích thành các thành phần P, L, U. In kết quả
print('\n*** Áp dụng phân rã PLU:')
P_T, L, U = lu(A)

print('Ma trận P_T', P_T.shape, ':\n', P_T)
print('Ma trận L', L.shape, ':\n', L)
print('Ma trận U', U.shape, ':\n', U)

print('\nTái tạo A từ P, L, U (kiểm chứng lại phép phân rã):\n', P_T.dot(L).dot(U), '\n')

##------------------------------------------------------------------------------
## Mở rộng cho ma trận hình chữ nhật
##------------------------------------------------------------------------------
A = np.array([[1, 2,  4, 3], 
              [3, 8, 14, 0],
              [2, 6, 13, 2]])
P_T, L, U = lu(A)

print('Ma trận HÌNH CHỮ NHẬT A\n', A.shape,'\n', A)
print('\n*** Áp dụng phân rã PLU')
print('Ma trận P_T', P_T.shape, ':\n', P_T)
print('Ma trận L', L.shape, ':\n', L)
print('Ma trận U', U.shape, ':\n', U)
print('\nTái tạo A từ P, L, U (kiểm chứng lại phép phân rã):\n', P_T.dot(L).dot(U), '\n')




Ma trận VUÔNG A (4, 4) :
 [[ 6  6  7  8]
 [ 2  8  2  2]
 [ 2 10  5  9]
 [ 9  4  7  2]]

*** Áp dụng phân rã PLU:
Ma trận P_T (4, 4) :
 [[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]
Ma trận L (4, 4) :
 [[ 1.          0.          0.          0.        ]
 [ 0.22222222  1.          0.          0.        ]
 [ 0.22222222  0.7804878   1.          0.        ]
 [ 0.66666667  0.36585366 -0.47826087  1.        ]]
Ma trận U (4, 4) :
 [[ 9.          4.          7.          2.        ]
 [ 0.          9.11111111  3.44444444  8.55555556]
 [ 0.          0.         -2.24390244 -5.12195122]
 [ 0.          0.          0.          1.08695652]]

Tái tạo A từ P, L, U (kiểm chứng lại phép phân rã):
 [[ 6.  6.  7.  8.]
 [ 2.  8.  2.  2.]
 [ 2. 10.  5.  9.]
 [ 9.  4.  7.  2.]] 

Ma trận HÌNH CHỮ NHẬT A
 (3, 4) 
 [[ 1  2  4  3]
 [ 3  8 14  0]
 [ 2  6 13  2]]

*** Áp dụng phân rã PLU
Ma trận P_T (3, 3) :
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Ma trận L (3, 3) :
 [[ 1.          0.          0.        

In [3]:
"""=============================================================================
Ex1: DECOMPOSITION
    Câu 2: Giải hệ phương trình bằng LU Decomposition
        a) Quy về Ax = B. Sau đó giải tìm x.
        b) Phân tích thành các thành phần P, L, U. In kết quả.
        c) Tái tạo lại ma trận A từ các thành phần P, L, U.
============================================================================="""
import numpy        as np    
import scipy.linalg as linalg

from scipy.linalg import lu

## Câu 2
A = np.array([[2, 1, 1], 
              [1, 3, 2], 
              [1, 0, 0]])
B = np.array([4, 5, 6]) 

## Ví dụ thêm
A = np.array([[10, 8, 10,  8], 
              [ 8, 6,  6, 10], 
              [ 3, 3,  6,  3],
              [11, 8,  6,  1]])
B = np.array([4, 5, 6, 7]) 

print('Ma trận A', A.shape, ':\n', A)

print('\n************************ Hàm scipy.linalg.lu() ***********************')
P_T, L, U = lu(A)

print('Ma trận P_T', P_T.shape, ':\n', P_T, '\n')
print('Ma trận L', L.shape, ':\n', L, '\n')
print('Ma trận U', U.shape, ':\n', U, '\n')


print('\n********************* Hàm scipy.linalg.lu_factor() *******************')
## //docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.lu_factor.html
##    Hàm lu_factor(A) trả về 2 đối tượng:
##       - Ma trận nxn: U + (L - diag(L))
##       - Mảng [n] chứa các chỉ số dòng của I(n) để tạo nên P
##------------------------------------------------------------------------------
## Hàm tạo ma trận hoán vị P từ pivot = linalg.lu_factor(A)[1]
def permutationMatrix(pivot):
    # Khởi tạo P bằng ma trận đơn vị
    P = np.identity(len(pivot))

    # i: index; r: element
    for i, r in enumerate(pivot):
        # pivot[i] = r
        # Hoán đổi dòng i và dòng pivot[i] của ma trận I
    
        I = np.identity(len(pivot))
    
        temp    = I[i, :].copy()
        I[i, :] = I[r, :]
        I[r, :] = temp 
        
        P = P.dot(I)
    return P
##------------------------------------------------------------------------------

LU = linalg.lu_factor(A)

print('Ma trận kết hợp U + L - diag(L)', LU[0].shape, ':\n', LU[0])

U = np.triu(LU[0])
L = LU[0] - U + np.identity(len(B))

print('Ma trận L', L.shape, ':\n', L, '\n')
print('Ma trận U', U.shape, ':\n', U, '\n')

## Ma trận hoán vị
print('Mảng pivot', LU[1].shape, ':\n', LU[1])
P = permutationMatrix(LU[1])
print('Ma trận hoán vị P', P.shape, ':\n', P, '\n')

x = linalg.lu_solve(LU, B)
print("Hệ nghiệm [xi] =", x)


Ma trận A (4, 4) :
 [[10  8 10  8]
 [ 8  6  6 10]
 [ 3  3  6  3]
 [11  8  6  1]]

************************ Hàm scipy.linalg.lu() ***********************
Ma trận P_T (4, 4) :
 [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 

Ma trận L (4, 4) :
 [[1.         0.         0.         0.        ]
 [0.27272727 1.         0.         0.        ]
 [0.90909091 0.88888889 1.         0.        ]
 [0.72727273 0.22222222 1.         1.        ]] 

Ma trận U (4, 4) :
 [[11.          8.          6.          1.        ]
 [ 0.          0.81818182  4.36363636  2.72727273]
 [ 0.          0.          0.66666667  4.66666667]
 [ 0.          0.          0.          4.        ]] 


********************* Hàm scipy.linalg.lu_factor() *******************
Ma trận kết hợp U + L - diag(L) (4, 4) :
 [[11.          8.          6.          1.        ]
 [ 0.27272727  0.81818182  4.36363636  2.72727273]
 [ 0.90909091  0.88888889  0.66666667  4.66666667]
 [ 0.72727273  0.22222222  1.          4.        ]]
Ma tr