In [ ]:
# Tạo trang R trên colab: https://colab.research.google.com/notebook#create=true&language=r
a <- 5
b <- 7
c <- a + b

In [ ]:
fruit <- c("a",'b','c')

In [ ]:
print(fruit)

[1] "a" "b" "c"


In [ ]:
print(c)

[1] 12


In [ ]:
M=matrix(c(1:12), nrow=4, ncol=3, byrow=TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [ ]:
N=matrix(c(1:12), nrow=4, ncol=3, byrow=FALSE)
print(N)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


In [ ]:
N=matrix(c(1:12), nrow=4, byrow=TRUE)

In [ ]:
rownames=c("row1", "row2", "row3", "row4")
colnames=c("col1", "col2", "col3")

In [ ]:
P=matrix(c(1:12), nrow=4, byrow=TRUE, dimnames=list(rownames, colnames))
print(P)

     col1 col2 col3
row1    1    2    3
row2    4    5    6
row3    7    8    9
row4   10   11   12


In [ ]:
print(P[1,3])

[1] 3


In [ ]:
print(P[4,2])

[1] 11


In [ ]:
print(P[2,])

col1 col2 col3 
   4    5    6 


In [ ]:
print(P[,3])

row1 row2 row3 row4 
   3    6    9   12 


In [ ]:
M1=matrix(c(3:14), nrow=2, byrow=TRUE)
M2=matrix(c(1:12), nrow=4, byrow=TRUE)

In [ ]:
print(M1)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    3    4    5    6    7    8    9
[2,]   10   11   12   13   14   15   16


In [ ]:
print(M2)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12
[4,]   13   14   15   16


In [ ]:
result_add=M1+M2
cat("Result of addition","\n")
print(result_add)

Result of addition 
     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    4    6    8   10   12   14   16
[2,]   18   20   22   24   26   28   30


In [ ]:
mat1=matrix(c(3:18), ncol=4, byrow=TRUE)
mat2=matrix(c(1:16), nrow=4, byrow=TRUE)

In [ ]:
mat3=mat1%*%mat2

In [ ]:
print(mat3)

     [,1] [,2] [,3] [,4]
[1,]  146  164  182  200
[2,]  258  292  326  360
[3,]  370  420  470  520
[4,]  482  548  614  680


In [ ]:
vec=c(1:3)
mat=matrix(c(1:9), ncol=3)
print(vec)
print(mat)

[1] 1 2 3
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [ ]:
vec_new=mat%*%vec
print(vec_new)

     [,1]
[1,]   30
[2,]   36
[3,]   42


In [ ]:
v1=c(1:6)
v2=c(7:15)

In [ ]:
array1=array(v1, dim=c(3,2,2))
print(array1)

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6



In [ ]:
array2=array(c(v1,v2), dim=c(3,4,2))
print(array2)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13    1    4    7
[2,]   14    2    5    8
[3,]   15    3    6    9



In [ ]:
row_names=c("row1", "row2", "row3")
col_names=c("col1", "col2", "col3", "col4")
mat_names=c("matrix1","matrix2")
array3=array(c(v1,v2), dim=c(3,4,2), dimnames=list(row_names, col_names, mat_names))
print(array3)

, , matrix1

     col1 col2 col3 col4
row1    1    4    7   10
row2    2    5    8   11
row3    3    6    9   12

, , matrix2

     col1 col2 col3 col4
row1   13    1    4    7
row2   14    2    5    8
row3   15    3    6    9



In [ ]:
print(array3[3,2,1])

[1] 6


In [ ]:
print(array3[1,,2])

col1 col2 col3 col4 
  13    1    4    7 


In [ ]:
print(array3[,,2])

     col1 col2 col3 col4
row1   13    1    4    7
row2   14    2    5    8
row3   15    3    6    9


In [ ]:
print(array3[,3,1])

row1 row2 row3 
   7    8    9 


In [ ]:
print(apply(array3, c(1),sum))

row1 row2 row3 
  47   55   63 


In [ ]:
print(apply(array3, c(2),min))

col1 col2 col3 col4 
   1    1    4    7 


In [ ]:
print(apply(array3, c(3),mean))

matrix1 matrix2 
   6.50    7.25 


In [ ]:
list_data=list("hello", "R", 12, 25.5, c(21,32, 11), TRUE)
print(list_data)

[[1]]
[1] "hello"

[[2]]
[1] "R"

[[3]]
[1] 12

[[4]]
[1] 25.5

[[5]]
[1] 21 32 11

[[6]]
[1] TRUE



In [ ]:
list_1=list(c("Red", "Green", "Yello"), matrix(c(1:8),nrow=2), list("green", TRUE, 12.5), TRUE)

In [ ]:
names(list_1)=c("Traffic Light", "A_Matrix", "An Inner List", "Pass")

In [ ]:
print(list_1)

$`Traffic Light`
[1] "Red"   "Green" "Yello"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`An Inner List`
$`An Inner List`[[1]]
[1] "green"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] TRUE



In [ ]:
print(list_1[1])

$`Traffic Light`
[1] "Red"   "Green" "Yello"



In [ ]:
print(list_1$A_Matrix)

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8


In [ ]:
list_1[length(list_1)+1]="New element"

In [ ]:
print(list_1[length(list_1)])

[[1]]
[1] "New element"



In [ ]:
list_1[length(list_1)]=NULL

In [ ]:
list_1

$`Traffic Light`
[1] "Red"   "Green" "Yello"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`An Inner List`
$`An Inner List`[[1]]
[1] "green"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] TRUE

In [ ]:
list_1[3]=TRUE

In [ ]:
print(list_1[3])

$`An Inner List`
[1] TRUE



In [ ]:
list1=list(1, TRUE, c("Red", "Green", "Yellow"))
list2=list(TRUE, "hello", 12.5)

In [ ]:
merged.list=c(list1, list2)

In [ ]:
print(merged.list)

[[1]]
[1] 1

[[2]]
[1] TRUE

[[3]]
[1] "Red"    "Green"  "Yellow"

[[4]]
[1] TRUE

[[5]]
[1] "hello"

[[6]]
[1] 12.5



In [ ]:
list1=list(1:5)
list2=list(6:10)
v1=unlist(list1)
v2=unlist(list2)

In [ ]:
print(v1)
print(v2)

[1] 1 2 3 4 5
[1]  6  7  8  9 10


In [ ]:
students_1=data.frame("name"=c('Helen', 'Jolie', 'Kiwi', 'John', 'Mark', 'Tom'), "age"=c(17,16,17,18,19,16), "mark"= c(9,9,8,7.5,7.5,8), stringsAsFactors=FALSE)
print(students_1)

   name age mark
1 Helen  17  9.0
2 Jolie  16  9.0
3  Kiwi  17  8.0
4  John  18  7.5
5  Mark  19  7.5
6   Tom  16  8.0


In [ ]:
"name"=c('Helen', 'Jolie', 'Kiwi', 'John', 'Mark', 'Tom')
"age"=c(17,16,17,18,19,16)
"mark"= c(9,9,8,7.5,7.5,8)
students=data.frame(name, age, mark, stringsAsFactors=FALSE)

In [ ]:
print(students)

   name age mark
1 Helen  17  9.0
2 Jolie  16  9.0
3  Kiwi  17  8.0
4  John  18  7.5
5  Mark  19  7.5
6   Tom  16  8.0


In [ ]:
str(students)

'data.frame':	6 obs. of  3 variables:
 $ name: chr  "Helen" "Jolie" "Kiwi" "John" ...
 $ age : num  17 16 17 18 19 16
 $ mark: num  9 9 8 7.5 7.5 8


In [ ]:
print(summary(students))

     name                age             mark      
 Length:6           Min.   :16.00   Min.   :7.500  
 Class :character   1st Qu.:16.25   1st Qu.:7.625  
 Mode  :character   Median :17.00   Median :8.000  
                    Mean   :17.17   Mean   :8.167  
                    3rd Qu.:17.75   3rd Qu.:8.750  
                    Max.   :19.00   Max.   :9.000  


In [ ]:
print(students$mark)

[1] 9.0 9.0 8.0 7.5 7.5 8.0


In [ ]:
print(data.frame(students$age))

  students.age
1           17
2           16
3           17
4           18
5           19
6           16


In [ ]:
print(students[1:2,])

   name age mark
1 Helen  17    9
2 Jolie  16    9


In [ ]:
print(students[c(3,5), c(1,2)])

  name age
3 Kiwi  17
5 Mark  19


In [ ]:
students$class=c("k256_S7N","k256_C7N", "k256_S7N","k256_S24", "k256_S24", "k256_C7N")
students

name  age mark class   
1 Helen 17  9.0  k256_S7N
2 Jolie 16  9.0  k256_C7N
3 Kiwi  17  8.0  k256_S7N
4 John  18  7.5  k256_S24
5 Mark  19  7.5  k256_S24
6 Tom   16  8.0  k256_C7N

In [ ]:
df_POB=data.frame("POB"=c("UK","US","EU","UK", "US", "EU"))
students=cbind(students, df_POB)

In [ ]:
students

name  age mark class    POB
1 Helen 17  9.0  k256_S7N UK 
2 Jolie 16  9.0  k256_C7N US 
3 Kiwi  17  8.0  k256_S7N EU 
4 John  18  7.5  k256_S24 UK 
5 Mark  19  7.5  k256_S24 US 
6 Tom   16  8.0  k256_C7N EU

In [ ]:
new_students=data.frame("name"=c('Sunny','Lucy'),"age"=c(17,18),"mark"=c(8,9),"class"=c("k256_C7N","k256_S24"),'POB'=c("EU","UK"),stringsAsFactors=FALSE)

In [ ]:
print(new_students)

   name age mark    class POB
1 Sunny  17    8 k256_C7N  EU
2  Lucy  18    9 k256_S24  UK


In [ ]:
students=rbind(students, new_students)

In [ ]:
students

name  age mark class    POB
1 Helen 17  9.0  k256_S7N UK 
2 Jolie 16  9.0  k256_C7N US 
3 Kiwi  17  8.0  k256_S7N EU 
4 John  18  7.5  k256_S24 UK 
5 Mark  19  7.5  k256_S24 US 
6 Tom   16  8.0  k256_C7N EU 
7 Sunny 17  8.0  k256_C7N EU 
8 Lucy  18  9.0  k256_S24 UK

In [ ]:
names(students)[names(students)=="POB"]="Place_of_birth"
head(students)

name  age mark class    Place_of_birth
1 Helen 17  9.0  k256_S7N UK            
2 Jolie 16  9.0  k256_C7N US            
3 Kiwi  17  8.0  k256_S7N EU            
4 John  18  7.5  k256_S24 UK            
5 Mark  19  7.5  k256_S24 US            
6 Tom   16  8.0  k256_C7N EU