# Bài tập tuần 2
## Bài tập số 1:

In [ ]:
# Definition of survey_vector
survey_vector <- c("R", "R", "L", "L", "R", "R", "C", "C")

# Create survey_vector as a factor: survey_factor
survey_factor=factor(survey_vector)

# Print survey_factor
print(survey_factor)

# Print levels of survey_factor
print("levels of survey_factor")
levels(survey_factor)

# Print nlevels of survey_factor
print(paste("nlevels of survey_factor:",nlevels(survey_factor)))
# How many elements of each factor?
print(paste("elements of each factor"))
summary(survey_factor)

[1] R R L L R R C C
Levels: C L R
[1] "levels of survey_factor"


[1] "C" "L" "R"

[1] "nlevels of survey_factor: 3"
[1] "elements of each factor"


C L R 
2 2 4

## Bài tập số 2:


In [ ]:
# Create my_vector: 1 up to 10
my_vector=c(1:10)
# Create my_matrix (3x3): 1 up to 9
my_matrix=matrix(c(1:9), nrow=3, ncol=3, byrow=TRUE)
# Create my_factor from sizes
sizes <-c("M","S","L","L","M")

# Construct my_list with the three data structures above
my_list=list(my_vector, my_matrix,sizes)
# Construct my_super_list with the four data structures above
my_super_list=list(my_vector, my_matrix,sizes,my_list)
# Display structure of my_super_list (Use str())
str(my_super_list)
# Print my_matrix, sum of my_matrix, sum of even elements in my_matrix
print("my_matrix")
my_matrix
print(paste("sum of my_matrix:", sum(my_matrix)))


List of 4
 $ : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ : int [1:3, 1:3] 1 4 7 2 5 8 3 6 9
 $ : chr [1:5] "M" "S" "L" "L" ...
 $ :List of 3
  ..$ : int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ : int [1:3, 1:3] 1 4 7 2 5 8 3 6 9
  ..$ : chr [1:5] "M" "S" "L" "L" ...
[1] "my_matrix"


[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[1] "sum of my_matrix: 45"


In [ ]:
#C1
odd_even <- function(x) c("odd"=sum(x%%2), "even"=sum(!x%%2))
odd_even(my_matrix)

odd even 
   5    4

In [ ]:
#C2
even_odd <- function(x) setNames(table(x %% 2), c("even", "odd"))
even_odd(my_matrix)

even  odd 
   4    5 

In [ ]:
a=0
for (i in my_matrix){
if (i%% 2 ==0){
  a=a+i}}
print(paste("sum of even elements in my_matrix:",a))


[1] "sum of even elements in my_matrix: 20"


## Bài tập số 3:


In [ ]:
# Create my_matrix (4x4): each element is a randomly generated prime number.

# Sum the elements on the main diagonal of the matrix

# (Note: Build function to create_matrix, function to test_Prime number, and function to Sum... >> Call fucntion)


In [3]:
install.packages("primes")
library("primes")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependency ‘Rcpp’




In [4]:
primes=generate_n_primes(100)
v1=sample(primes, 16)
my_matrix=matrix(v1, nrow=4, ncol=4, byrow=TRUE)

In [5]:
matrix.function <- function(primes){
  v1=sample(primes, 16)
  my_matrix=matrix(v1, nrow=4, ncol=4, byrow=TRUE)
  return (my_matrix)
}
matrix.function(primes)

[,1] [,2] [,3] [,4]
[1,] 461   67  503  179 
[2,]  73  541   43    3 
[3,] 431   83  269  271 
[4,] 457  239  283  439

In [ ]:
my_matrix

[,1] [,2] [,3] [,4]
[1,]  23  199  307   83 
[2,] 269  197  503  401 
[3,] 317  353  311  241 
[4,] 383  283  251  443

In [ ]:
sum(diag(my_matrix))

[1] 974

## Bài tập số 4:

In [ ]:
# Create my_array (4, 4, 2): from 2 matrices created by calling function create_matrix (Bai tap so 3)

# Use apply to calculate the min of the rows across all the matrices.

# Use apply to calculate the max of the columns across all the matrices.

# Use apply to calculate the sum of each matrix in my_array

In [6]:
matrix1=matrix.function(primes)
matrix2=matrix.function(primes)
print(matrix1)
print(matrix2)

     [,1] [,2] [,3] [,4]
[1,]  293  311  151  233
[2,]  163  499  383  281
[3,]   67  409   97  167
[4,]  523   43   73   79
     [,1] [,2] [,3] [,4]
[1,]   19  373  233  347
[2,]   31   73  433  149
[3,]  409  107  313   61
[4,]   79   41  337  257


In [13]:
result <- array(c(matrix1,matrix2),,dim = c(4,4,2))
print(result)

, , 1

     [,1] [,2] [,3] [,4]
[1,]  293  311  151  233
[2,]  163  499  383  281
[3,]   67  409   97  167
[4,]  523   43   73   79

, , 2

     [,1] [,2] [,3] [,4]
[1,]   19  373  233  347
[2,]   31   73  433  149
[3,]  409  107  313   61
[4,]   79   41  337  257



In [40]:
apply(result, c(1), min)

[1] 19 31 61 41

In [41]:
apply(result, c(2), max)

[1] 523 499 433 347

In [43]:
i=1
dims=dim(result)[3]
while(i<=dims){
print(sum(apply(result[,,i], 1, sum)))
i <- i+1
}

[1] 3772
[1] 3262


## Bài tập số 5

In [44]:
# Create title, actors, reviews
title = "The Shining"
actors_vector <- c("Jack Nicholson","Shelley Duvall","Danny Lloyd","Scatman Crothers","Barry Nelson")
reviews_factor <- factor(c("Good", "OK", "Good", "Perfect", "Bad", "Perfect", "Good"), 
                  ordered = TRUE, levels = c("Bad", "OK", "Good", "Perfect"))

# Create the list 'shining_list' from 3 vectors above

# Select the last actor from list: last_actor

# Select the second review from list: second_review

# Add the element 'release_year' = 1980 to shining_list

# Add the element 'director' = "Stanley Kubrick" to shining_list

# Print list shining_list

# Print the structure of shining_list

In [45]:
shining_list <- list(title, actors_vector, reviews_factor)


[[1]]
[1] "The Shining"

[[2]]
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

[[3]]
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect



In [48]:
last_actor=shining_list[[2]][length(actors_vector)]
last_actor

[1] "Barry Nelson"

In [49]:
second_review=shining_list[[3]][2]
second_review

[1] OK
Levels: Bad < OK < Good < Perfect

In [51]:
shining_list[[4]]=1980

In [53]:
shining_list[[5]]="Stanley Kubrick"

In [55]:
print(shining_list)

[[1]]
[1] "The Shining"

[[2]]
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

[[3]]
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

[[4]]
[1] 1980

[[5]]
[1] "Stanley Kubrick"



In [54]:
str(shining_list)

List of 5
 $ : chr "The Shining"
 $ : chr [1:5] "Jack Nicholson" "Shelley Duvall" "Danny Lloyd" "Scatman Crothers" ...
 $ : Ord.factor w/ 4 levels "Bad"<"OK"<"Good"<..: 3 2 3 4 1 4 3
 $ : num 1980
 $ : chr "Stanley Kubrick"


## Bài tập số 6: Hãy thực hiện những yêu cầu sau với R-core dataframe và/ hoặc Tidyverse
1. Cho dữ liệu mtcars cho sẵn trong R datasets. Đọc dữ liệu. Hiển thị thông tin một số dòng đầu của dữ liệu. In thông tin thống kê chung.
2. Tạo sub_data chỉ có các thông tin mpg, hp, wt, gear
3. Tạp cột mới km_per_litre trong sub_data theo công thức: 1 mpg = 0.425 km/l
4. Tạo sub_data_unique lấy từ mtcars nhưng loại bỏ các dòng trùng (dùng distinct()
5. In sub_data_unique với giá trị được sắp xếp giảm dần theo mpg, tăng dần theo hp
6. Lọc các xe mà trong tên xe có 'Mazda' trong sub_data_unique. Có bao nhiêu xe thỏa điều kiện này?
7. Trong sub_data_unique, cho biết giá trị mpg lớn nhất? Có những dòng dữ liệu nào có mpg = mpg lớn nhất, in kết quả.
8. Lọc các dữ liệu thỏa các điểu kiện sau: mpg >= 25 và cyl=4 và gear=4
9. Thực hiện việc thống kê theo cyl, từ đó cho biết số lượng từng nhóm, cyl, hp lớn nhất, mpg nhỏ nhất
10. Trong sub_data, cho biết xe nào có km_per_litre lớn nhất, nhỏ nhất?

#### Note: dùng df = cbind(names = rownames(df), df) hoặc rownames_to_column(df, var = "names"): chuyển cột index thành cột "names"