In [ ]:
# Tạo trang R trên colab: https://colab.research.google.com/notebook#create=true&language=r
a <- 5
b <- 7
c <- a + b

In [ ]:
fruit <- c("a",'b','c')

In [ ]:
print(fruit)

[1] "a" "b" "c"


In [ ]:
print(c)

[1] 12


In [ ]:
M=matrix(c(1:12), nrow=4, ncol=3, byrow=TRUE)
print(M)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12


In [ ]:
N=matrix(c(1:12), nrow=4, ncol=3, byrow=FALSE)
print(N)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12


In [ ]:
N=matrix(c(1:12), nrow=4, byrow=TRUE)

In [ ]:
rownames=c("row1", "row2", "row3", "row4")
colnames=c("col1", "col2", "col3")

In [ ]:
P=matrix(c(1:12), nrow=4, byrow=TRUE, dimnames=list(rownames, colnames))
print(P)

     col1 col2 col3
row1    1    2    3
row2    4    5    6
row3    7    8    9
row4   10   11   12


In [ ]:
print(P[1,3])

[1] 3


In [ ]:
print(P[4,2])

[1] 11


In [ ]:
print(P[2,])

col1 col2 col3 
   4    5    6 


In [ ]:
print(P[,3])

row1 row2 row3 row4 
   3    6    9   12 


In [ ]:
M1=matrix(c(3:14), nrow=2, byrow=TRUE)
M2=matrix(c(1:12), nrow=4, byrow=TRUE)

In [ ]:
print(M1)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    3    4    5    6    7    8    9
[2,]   10   11   12   13   14   15   16


In [ ]:
print(M2)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12
[4,]   13   14   15   16


In [ ]:
result_add=M1+M2
cat("Result of addition","\n")
print(result_add)

Result of addition 
     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
[1,]    4    6    8   10   12   14   16
[2,]   18   20   22   24   26   28   30


In [ ]:
mat1=matrix(c(3:18), ncol=4, byrow=TRUE)
mat2=matrix(c(1:16), nrow=4, byrow=TRUE)

In [ ]:
mat3=mat1%*%mat2

In [ ]:
print(mat3)

     [,1] [,2] [,3] [,4]
[1,]  146  164  182  200
[2,]  258  292  326  360
[3,]  370  420  470  520
[4,]  482  548  614  680


In [ ]:
vec=c(1:3)
mat=matrix(c(1:9), ncol=3)
print(vec)
print(mat)

[1] 1 2 3
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9


In [ ]:
vec_new=mat%*%vec
print(vec_new)

     [,1]
[1,]   30
[2,]   36
[3,]   42


In [ ]:
v1=c(1:6)
v2=c(7:15)

In [ ]:
array1=array(v1, dim=c(3,2,2))
print(array1)

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6



In [ ]:
array2=array(c(v1,v2), dim=c(3,4,2))
print(array2)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13    1    4    7
[2,]   14    2    5    8
[3,]   15    3    6    9



In [ ]:
row_names=c("row1", "row2", "row3")
col_names=c("col1", "col2", "col3", "col4")
mat_names=c("matrix1","matrix2")
array3=array(c(v1,v2), dim=c(3,4,2), dimnames=list(row_names, col_names, mat_names))
print(array3)

, , matrix1

     col1 col2 col3 col4
row1    1    4    7   10
row2    2    5    8   11
row3    3    6    9   12

, , matrix2

     col1 col2 col3 col4
row1   13    1    4    7
row2   14    2    5    8
row3   15    3    6    9



In [ ]:
print(array3[3,2,1])

[1] 6


In [ ]:
print(array3[1,,2])

col1 col2 col3 col4 
  13    1    4    7 


In [ ]:
print(array3[,,2])

     col1 col2 col3 col4
row1   13    1    4    7
row2   14    2    5    8
row3   15    3    6    9


In [ ]:
print(array3[,3,1])

row1 row2 row3 
   7    8    9 


In [ ]:
print(apply(array3, c(1),sum))

row1 row2 row3 
  47   55   63 


In [ ]:
print(apply(array3, c(2),min))

col1 col2 col3 col4 
   1    1    4    7 


In [ ]:
print(apply(array3, c(3),mean))

matrix1 matrix2 
   6.50    7.25 


In [ ]:
list_data=list("hello", "R", 12, 25.5, c(21,32, 11), TRUE)
print(list_data)

[[1]]
[1] "hello"

[[2]]
[1] "R"

[[3]]
[1] 12

[[4]]
[1] 25.5

[[5]]
[1] 21 32 11

[[6]]
[1] TRUE



In [ ]:
list_1=list(c("Red", "Green", "Yello"), matrix(c(1:8),nrow=2), list("green", TRUE, 12.5), TRUE)

In [ ]:
names(list_1)=c("Traffic Light", "A_Matrix", "An Inner List", "Pass")

In [ ]:
print(list_1)

$`Traffic Light`
[1] "Red"   "Green" "Yello"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`An Inner List`
$`An Inner List`[[1]]
[1] "green"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] TRUE



In [ ]:
print(list_1[1])

$`Traffic Light`
[1] "Red"   "Green" "Yello"



In [ ]:
print(list_1$A_Matrix)

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8


In [ ]:
list_1[length(list_1)+1]="New element"

In [ ]:
print(list_1[length(list_1)])

[[1]]
[1] "New element"



In [ ]:
list_1[length(list_1)]=NULL

In [ ]:
list_1

$`Traffic Light`
[1] "Red"   "Green" "Yello"

$A_Matrix
     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

$`An Inner List`
$`An Inner List`[[1]]
[1] "green"

$`An Inner List`[[2]]
[1] TRUE

$`An Inner List`[[3]]
[1] 12.5


$Pass
[1] TRUE

In [ ]:
list_1[3]=TRUE

In [ ]:
print(list_1[3])

$`An Inner List`
[1] TRUE



In [ ]:
list1=list(1, TRUE, c("Red", "Green", "Yellow"))
list2=list(TRUE, "hello", 12.5)

In [ ]:
merged.list=c(list1, list2)

In [ ]:
print(merged.list)

[[1]]
[1] 1

[[2]]
[1] TRUE

[[3]]
[1] "Red"    "Green"  "Yellow"

[[4]]
[1] TRUE

[[5]]
[1] "hello"

[[6]]
[1] 12.5



In [ ]:
list1=list(1:5)
list2=list(6:10)
v1=unlist(list1)
v2=unlist(list2)

In [ ]:
print(v1)
print(v2)

[1] 1 2 3 4 5
[1]  6  7  8  9 10


In [ ]:
students_1=data.frame("name"=c('Helen', 'Jolie', 'Kiwi', 'John', 'Mark', 'Tom'), "age"=c(17,16,17,18,19,16), "mark"= c(9,9,8,7.5,7.5,8), stringsAsFactors=FALSE)
print(students_1)

   name age mark
1 Helen  17  9.0
2 Jolie  16  9.0
3  Kiwi  17  8.0
4  John  18  7.5
5  Mark  19  7.5
6   Tom  16  8.0


In [ ]:
"name"=c('Helen', 'Jolie', 'Kiwi', 'John', 'Mark', 'Tom')
"age"=c(17,16,17,18,19,16)
"mark"= c(9,9,8,7.5,7.5,8)
students=data.frame(name, age, mark, stringsAsFactors=FALSE)

In [ ]:
print(students)

   name age mark
1 Helen  17  9.0
2 Jolie  16  9.0
3  Kiwi  17  8.0
4  John  18  7.5
5  Mark  19  7.5
6   Tom  16  8.0


In [ ]:
str(students)

'data.frame':	6 obs. of  3 variables:
 $ name: chr  "Helen" "Jolie" "Kiwi" "John" ...
 $ age : num  17 16 17 18 19 16
 $ mark: num  9 9 8 7.5 7.5 8


In [ ]:
print(summary(students))

     name                age             mark      
 Length:6           Min.   :16.00   Min.   :7.500  
 Class :character   1st Qu.:16.25   1st Qu.:7.625  
 Mode  :character   Median :17.00   Median :8.000  
                    Mean   :17.17   Mean   :8.167  
                    3rd Qu.:17.75   3rd Qu.:8.750  
                    Max.   :19.00   Max.   :9.000  


In [ ]:
print(students$mark)

[1] 9.0 9.0 8.0 7.5 7.5 8.0


In [ ]:
print(data.frame(students$age))

  students.age
1           17
2           16
3           17
4           18
5           19
6           16


In [ ]:
print(students[1:2,])

   name age mark
1 Helen  17    9
2 Jolie  16    9


In [ ]:
print(students[c(3,5), c(1,2)])

  name age
3 Kiwi  17
5 Mark  19


In [ ]:
students$class=c("k256_S7N","k256_C7N", "k256_S7N","k256_S24", "k256_S24", "k256_C7N")
students

name  age mark class   
1 Helen 17  9.0  k256_S7N
2 Jolie 16  9.0  k256_C7N
3 Kiwi  17  8.0  k256_S7N
4 John  18  7.5  k256_S24
5 Mark  19  7.5  k256_S24
6 Tom   16  8.0  k256_C7N

In [ ]:
df_POB=data.frame("POB"=c("UK","US","EU","UK", "US", "EU"))
students=cbind(students, df_POB)

In [ ]:
students

name  age mark class    POB
1 Helen 17  9.0  k256_S7N UK 
2 Jolie 16  9.0  k256_C7N US 
3 Kiwi  17  8.0  k256_S7N EU 
4 John  18  7.5  k256_S24 UK 
5 Mark  19  7.5  k256_S24 US 
6 Tom   16  8.0  k256_C7N EU

In [ ]:
new_students=data.frame("name"=c('Sunny','Lucy'),"age"=c(17,18),"mark"=c(8,9),"class"=c("k256_C7N","k256_S24"),'POB'=c("EU","UK"),stringsAsFactors=FALSE)

In [ ]:
print(new_students)

   name age mark    class POB
1 Sunny  17    8 k256_C7N  EU
2  Lucy  18    9 k256_S24  UK


In [ ]:
students=rbind(students, new_students)

In [ ]:
students

name  age mark class    POB
1 Helen 17  9.0  k256_S7N UK 
2 Jolie 16  9.0  k256_C7N US 
3 Kiwi  17  8.0  k256_S7N EU 
4 John  18  7.5  k256_S24 UK 
5 Mark  19  7.5  k256_S24 US 
6 Tom   16  8.0  k256_C7N EU 
7 Sunny 17  8.0  k256_C7N EU 
8 Lucy  18  9.0  k256_S24 UK

In [ ]:
names(students)[names(students)=="POB"]="Place_of_birth"
head(students)

name  age mark class    Place_of_birth
1 Helen 17  9.0  k256_S7N UK            
2 Jolie 16  9.0  k256_C7N US            
3 Kiwi  17  8.0  k256_S7N EU            
4 John  18  7.5  k256_S24 UK            
5 Mark  19  7.5  k256_S24 US            
6 Tom   16  8.0  k256_C7N EU

In [1]:
install.packages('tidyverse')

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [2]:
library(tidyverse)

Warning message in system("timedatectl", intern = TRUE):
“running command 'timedatectl' had status 1”
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──

✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.6     ✔ dplyr   1.0.8
✔ tidyr   1.2.0     ✔ stringr 1.4.0
✔ readr   2.1.2     ✔ forcats 0.5.1

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()



In [12]:
system("ls", TRUE)

[1] "sample_data"

In [14]:
#https://drive.google.com/file/d/1dFDda7yxSfENn9i-Oe9IMJ6VUTFHpZLK/view?usp=sharing
system('gdown --id 1dFDda7yxSfENn9i-Oe9IMJ6VUTFHpZLK')

In [15]:
pokemon=read.csv('pokemon.csv')

In [16]:
head(pokemon)

X. Name                  Type.1 Type.2 Total HP Attack Defense Sp..Atk
1 1  Bulbasaur             Grass  Poison 318   45  49     49      65    
2 2  Ivysaur               Grass  Poison 405   60  62     63      80    
3 3  Venusaur              Grass  Poison 525   80  82     83     100    
4 3  VenusaurMega Venusaur Grass  Poison 625   80 100    123     122    
5 4  Charmander            Fire          309   39  52     43      60    
6 5  Charmeleon            Fire          405   58  64     58      80    
  Sp..Def Speed Generation Legendary
1  65     45    1          False    
2  80     60    1          False    
3 100     80    1          False    
4 120     80    1          False    
5  50     65    1          False    
6  65     80    1          False

In [17]:
pokemon_sub=select(pokemon, c(2,5,7,8))

In [18]:
head(pokemon_sub)

Name                  Total Attack Defense
1 Bulbasaur             318    49     49    
2 Ivysaur               405    62     63    
3 Venusaur              525    82     83    
4 VenusaurMega Venusaur 625   100    123    
5 Charmander            309    52     43    
6 Charmeleon            405    64     58

In [19]:
pokemon_sub=pokemon %>% select(Name, Total, Attack, Defense)
head(pokemon_sub)

Name                  Total Attack Defense
1 Bulbasaur             318    49     49    
2 Ivysaur               405    62     63    
3 Venusaur              525    82     83    
4 VenusaurMega Venusaur 625   100    123    
5 Charmander            309    52     43    
6 Charmeleon            405    64     58

In [20]:
pokemon_numbers=select_if(pokemon, is_numeric)

Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”
Warning message:
“Deprecated”


In [21]:
head(pokemon_numbers)

X. Total HP Attack Defense Sp..Atk Sp..Def Speed Generation
1 1  318   45  49     49      65      65     45    1         
2 2  405   60  62     63      80      80     60    1         
3 3  525   80  82     83     100     100     80    1         
4 3  625   80 100    123     122     120     80    1         
5 4  309   39  52     43      60      50     65    1         
6 5  405   58  64     58      80      65     80    1

In [22]:
pokemon_500_600=filter(pokemon_sub, Total >=500, Total <=600)
head(pokemon_500_600)

Name                Total Attack Defense
1 Venusaur            525    82     83    
2 Charizard           534    84     78    
3 Blastoise           530    83    100    
4 PidgeotMega Pidgeot 579    80     80    
5 Nidoqueen           505    92     87    
6 Nidoking            505   102     77

In [ ]:
pokemon_A=filter(pokemon, Attack>Defense)

In [25]:
pokemon_attack_defense=filter(pokemon_sub, Attack>Defense)
head(pokemon_attack_defense)

Name                      Total Attack Defense
1 Charmander                309    52     43    
2 Charmeleon                405    64     58    
3 Charizard                 534    84     78    
4 CharizardMega Charizard X 634   130    111    
5 CharizardMega Charizard Y 634   104     78    
6 Weedle                    195    35     30

In [26]:
pokemon_sub=mutate(pokemon_sub, Compare= ifelse(Attack>Defense,1,0))
head(pokemon_sub)

Name                  Total Attack Defense Compare
1 Bulbasaur             318    49     49     0      
2 Ivysaur               405    62     63     0      
3 Venusaur              525    82     83     0      
4 VenusaurMega Venusaur 625   100    123     0      
5 Charmander            309    52     43     1      
6 Charmeleon            405    64     58     1

In [27]:
head(arrange(pokemon_sub, Total))

Name      Total Attack Defense Compare
1 Sunkern   180   30     30      0      
2 Azurill   190   20     40      0      
3 Kricketot 194   25     41      0      
4 Caterpie  195   30     35      0      
5 Weedle    195   35     30      1      
6 Wurmple   195   45     35      1

In [28]:
head(arrange(pokemon_sub, desc(Total)))

Name                  Total Attack Defense Compare
1 MewtwoMega Mewtwo X   780   190    100     1      
2 MewtwoMega Mewtwo Y   780   150     70     1      
3 RayquazaMega Rayquaza 780   180    100     1      
4 KyogrePrimal Kyogre   770   150     90     1      
5 GroudonPrimal Groudon 770   180    160     1      
6 Arceus                720   120    120     0

In [29]:
head(arrange(pokemon_sub, desc(Total), desc(Attack)))

Name                  Total Attack Defense Compare
1 MewtwoMega Mewtwo X   780   190    100     1      
2 RayquazaMega Rayquaza 780   180    100     1      
3 MewtwoMega Mewtwo Y   780   150     70     1      
4 GroudonPrimal Groudon 770   180    160     1      
5 KyogrePrimal Kyogre   770   150     90     1      
6 Arceus                720   120    120     0

In [30]:
group=group_by(pokemon, Type.1)
sum_data=summarize(group, count =n(), mean.Attack=mean(Attack, na.rm=T), median.Attack=median(Attack, na.rm=T), mean.Defense=mean(Attack, na.rm=T), median.Defense=median(Attack, na.rm=T))

In [32]:
sum_data

Type.1   count mean.Attack median.Attack mean.Defense median.Defense
1  Bug       69    70.97101    65.0          70.97101     65.0         
2  Dark      31    88.38710    88.0          88.38710     88.0         
3  Dragon    32   112.12500   113.5         112.12500    113.5         
4  Electric  44    69.09091    65.0          69.09091     65.0         
5  Fairy     17    61.52941    52.0          61.52941     52.0         
6  Fighting  27    96.77778   100.0          96.77778    100.0         
7  Fire      52    84.76923    84.5          84.76923     84.5         
8  Flying     4    78.75000    85.0          78.75000     85.0         
9  Ghost     32    73.78125    66.0          73.78125     66.0         
10 Grass     70    73.21429    70.0          73.21429     70.0         
11 Ground    32    95.75000    85.0          95.75000     85.0         
12 Ice       24    72.75000    67.0          72.75000     67.0         
13 Normal    98    73.46939    70.5          73.46939     70.5         
14 Poison    28    74.67857    74.0          74.67857     74.0         
15 Psychic   57    71.45614    57.0          71.45614     57.0         
16 Rock      44    92.86364    95.0          92.86364     95.0         
17 Steel     27    92.70370    89.0          92.70370     89.0         
18 Water    112    74.15179    72.0          74.15179     72.0

In [33]:
count(pokemon, Type.1)

Type.1   n  
1  Bug       69
2  Dark      31
3  Dragon    32
4  Electric  44
5  Fairy     17
6  Fighting  27
7  Fire      52
8  Flying     4
9  Ghost     32
10 Grass     70
11 Ground    32
12 Ice       24
13 Normal    98
14 Poison    28
15 Psychic   57
16 Rock      44
17 Steel     27
18 Water    112

In [34]:
pokemon %>% sample_n(5)

X.  Name    Type.1   Type.2 Total HP  Attack Defense Sp..Atk Sp..Def Speed
1 145 Zapdos  Electric Flying 580    90  90     85     125     90      100  
2 372 Shelgon Dragon          420    65  95    100      60     50       50  
3  14 Kakuna  Bug      Poison 205    45  25     50      25     25       35  
4 667 Litleo  Fire     Normal 369    62  50     58      73     54       72  
5 717 Yveltal Dark     Flying 680   126 131     95     131     98       99  
  Generation Legendary
1 1          True     
2 3          False    
3 1          False    
4 6          False    
5 6          True

In [35]:
sub_5_per=pokemon %>%sample_frac(0.05)
dim(sub_5_per)

[1] 40 13