In [44]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [45]:
warnings.filterwarnings("ignore")

In [46]:
df = pd.DataFrame({
    'Name': ['Lucy', 'John', 'Tom', 'Mary', 'Mark'],
    'PlaceOfBirth': ['NewJork', 'London', 'HaNoi', 'BinhDuong', 'Dubai'],
    'Age': [24, 29, 21, 30, 27]
})
df

Name PlaceOfBirth  Age
0  Lucy      NewJork   24
1  John       London   29
2   Tom        HaNoi   21
3  Mary    BinhDuong   30
4  Mark        Dubai   27

In [47]:
df['PlaceOfBirth'].unique()

array(['NewJork', 'London', 'HaNoi', 'BinhDuong', 'Dubai'], dtype=object)

In [48]:
from sklearn.preprocessing import OneHotEncoder

In [49]:
# khởi tạo encoder
encoder = OneHotEncoder()

In [50]:
# mã hóa thuộc tính
df_encode = encoder.fit_transform(df[['PlaceOfBirth']]).toarray()
df_encode

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [51]:
encoder.categories_

[array(['BinhDuong', 'Dubai', 'HaNoi', 'London', 'NewJork'], dtype=object)]

In [52]:
# chuyển về dataframe
df_encode = pd.DataFrame(df_encode, columns = encoder.categories_[0])
df_encode

BinhDuong  Dubai  HaNoi  London  NewJork
0        0.0    0.0    0.0     0.0      1.0
1        0.0    0.0    0.0     1.0      0.0
2        0.0    0.0    1.0     0.0      0.0
3        1.0    0.0    0.0     0.0      0.0
4        0.0    1.0    0.0     0.0      0.0

In [53]:
df_new = pd.concat([df, df_encode], axis = 1)
df_new

Name PlaceOfBirth  Age  BinhDuong  Dubai  HaNoi  London  NewJork
0  Lucy      NewJork   24        0.0    0.0    0.0     0.0      1.0
1  John       London   29        0.0    0.0    0.0     1.0      0.0
2   Tom        HaNoi   21        0.0    0.0    1.0     0.0      0.0
3  Mary    BinhDuong   30        1.0    0.0    0.0     0.0      0.0
4  Mark        Dubai   27        0.0    1.0    0.0     0.0      0.0

In [54]:
#để tránh trùng cột -> thêm tiền tố ở trước các cột mới tạo

In [55]:
df_encode2 = encoder.fit_transform(df['PlaceOfBirth'].values.reshape(-1,1)).toarray()
df_encode2

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [56]:
# chuyển về dataframe
df_encode2 = pd.DataFrame(df_encode2, 
                          columns = ['place_' + i for i in encoder.categories_[0]])
df_encode2

place_BinhDuong  place_Dubai  place_HaNoi  place_London  place_NewJork
0              0.0          0.0          0.0           0.0            1.0
1              0.0          0.0          0.0           1.0            0.0
2              0.0          0.0          1.0           0.0            0.0
3              1.0          0.0          0.0           0.0            0.0
4              0.0          1.0          0.0           0.0            0.0

In [57]:
df_new2 = pd.concat([df, df_encode2], axis = 1)
df_new2

Name PlaceOfBirth  Age  place_BinhDuong  place_Dubai  place_HaNoi  \
0  Lucy      NewJork   24              0.0          0.0          0.0   
1  John       London   29              0.0          0.0          0.0   
2   Tom        HaNoi   21              0.0          0.0          1.0   
3  Mary    BinhDuong   30              1.0          0.0          0.0   
4  Mark        Dubai   27              0.0          1.0          0.0   

   place_London  place_NewJork  
0           0.0            1.0  
1           1.0            0.0  
2           0.0            0.0  
3           0.0            0.0  
4           0.0            0.0

In [60]:
df_encode2 = df_encode2.drop(['place_BinhDuong'], axis = 1)

In [61]:
df_new3 = pd.concat([df, df_encode2], axis = 1)
df_new3

Name PlaceOfBirth  Age  place_Dubai  place_HaNoi  place_London  \
0  Lucy      NewJork   24          0.0          0.0           0.0   
1  John       London   29          0.0          0.0           1.0   
2   Tom        HaNoi   21          0.0          1.0           0.0   
3  Mary    BinhDuong   30          0.0          0.0           0.0   
4  Mark        Dubai   27          1.0          0.0           0.0   

   place_NewJork  
0            1.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0

## Bỏ bớt cột đầu tiên khi mã hóa

In [62]:
# khởi tạo encoder
encoder2 = OneHotEncoder(drop='first')

In [66]:
# mã hóa 
df_encode = encoder2.fit_transform(df[['PlaceOfBirth']]).toarray()
df_encode

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [67]:
encoder2.categories_

[array(['BinhDuong', 'Dubai', 'HaNoi', 'London', 'NewJork'], dtype=object)]

In [68]:
# chuyển về DataFrame
df_encode = pd.DataFrame(df_encode, 
                         columns=['place_' + i for i in encoder2.categories_[0][1:]])
df_encode

place_Dubai  place_HaNoi  place_London  place_NewJork
0          0.0          0.0           0.0            1.0
1          0.0          0.0           1.0            0.0
2          0.0          1.0           0.0            0.0
3          0.0          0.0           0.0            0.0
4          1.0          0.0           0.0            0.0

In [69]:
df_new3 = pd.concat([df, df_encode], axis=1)
df_new3

Name PlaceOfBirth  Age  place_Dubai  place_HaNoi  place_London  \
0  Lucy      NewJork   24          0.0          0.0           0.0   
1  John       London   29          0.0          0.0           1.0   
2   Tom        HaNoi   21          0.0          1.0           0.0   
3  Mary    BinhDuong   30          0.0          0.0           0.0   
4  Mark        Dubai   27          1.0          0.0           0.0   

   place_NewJork  
0            1.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0

In [70]:
df_new3.drop(['PlaceOfBirth'], axis=1, inplace=True)
df_new3

Name  Age  place_Dubai  place_HaNoi  place_London  place_NewJork
0  Lucy   24          0.0          0.0           0.0            1.0
1  John   29          0.0          0.0           1.0            0.0
2   Tom   21          0.0          1.0           0.0            0.0
3  Mary   30          0.0          0.0           0.0            0.0
4  Mark   27          1.0          0.0           0.0            0.0

In [71]:
df_new3['PlaceOfBirth_decode'] = encoder2.inverse_transform(df_new3[['place_Dubai', 'place_HaNoi', 'place_London', 'place_NewJork']])
df_new3

Name  Age  place_Dubai  place_HaNoi  place_London  place_NewJork  \
0  Lucy   24          0.0          0.0           0.0            1.0   
1  John   29          0.0          0.0           1.0            0.0   
2   Tom   21          0.0          1.0           0.0            0.0   
3  Mary   30          0.0          0.0           0.0            0.0   
4  Mark   27          1.0          0.0           0.0            0.0   

  PlaceOfBirth_decode  
0             NewJork  
1              London  
2               HaNoi  
3           BinhDuong  
4               Dubai