In [1]:
import numpy as np

In [4]:
# Câu 1: Tạo array arr có kích thước 3x3 với tất cả các giá trị đều là True. 

# Hiển thị các phần tử của array arr
a=np.array([["True","True","True"],["True","True","True"],["True","True","True"]])
print(a)

[['True' 'True' 'True']
 ['True' 'True' 'True']
 ['True' 'True' 'True']]


In [14]:
a=np.ones([3,3],dtype=bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [9]:
# Câu 2: Cho array arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]). 

# Hãy chuyển thành array 2 chiều có kích thước 3x3 và lưu vào arr_2D.

# Xem danh sách các phần tử của arr_2D. 

# Trong arr_2D. Chuyển cột 1 sang cột 3 và ngược lại. => Xem lại danh sách các phần tử của arr_2D
arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

arr_2D =arr_1D.reshape(3,3)
print(arr_2D)
arr_2D[:, [2, 0]] = arr_2D[:, [0, 2]]
print(arr_2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [10]:
# Câu 3: Sử dụng array arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại 

# Xem lại danh sách các phần tử của arr_2D
arr_2D[[0,1],:] = arr_2D[[1,0],:]
print(arr_2D)

[[5 4 3]
 [2 1 0]
 [8 7 6]]


In [16]:
# Câu 4: Sử dụng array arr_2D của câu 3, Đảo ngược các dòng của array arr_2D 

# Xem lại danh sách các phần tử của arr_2D
arr_2D[[0,1,2],:] = arr_2D[[2,1,0],:]
print(arr_2D)

[[8 7 6]
 [2 1 0]
 [5 4 3]]


In [17]:
# Câu 5: Sử dụng array arr_2D của câu 4, Đảo ngược các cột của array arr_2D => Xem lại danh sách các phần tử của arr_2D
arr_2D[:, [0,1,2]] = arr_2D[:, [2,1,0]]
print(arr_2D)

[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [26]:
# Câu 6: Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]),
# Kiểm tra xem trong array có giá trị rỗng nào không? 
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
print(arr_2D_null)
if np.isnan(arr_2D_null).any() ==True:
    print('Co gia tri null')

[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
Co gia tri null


In [28]:
# Câu 7: Sử dụng array arr_2D_null của câu 6, thay thế giá trị null bằng 0 => Xem lại danh sách các phần tử của arr_2D_null
np.nan_to_num(arr_2D_null, copy=True)

array([[1., 2., 3.],
       [0., 5., 6.],
       [7., 0., 9.],
       [4., 5., 6.]])