In [1]:
import numpy as np

In [16]:
#1. Tạo mảng ngẫu nhiên 10 phần tử số nguyên từ 10-29
np.random.seed(2)
arr1=np.random.randint(10,30,size=(10,))
print(arr1)

[18 25 23 18 21 28 21 18 17 12]


In [13]:
#2. Cho biết kiểu dữ liệu các phần tử của arr1
arr1.dtype

dtype('int32')

In [ ]:
#3. Cho biết dung lượng bộ nhớ của mảng arr1


In [15]:
#4. Tạo mảng arr2 là mảng arr1 nhưng có các giá trị chia hết cho 3 được thay bằng -1
arr2=arr1.copy()
arr2[arr2%3==0]=-1
print(arr2)

[-1 25 23 -1 -1 28 -1 -1 17 -1]


In [17]:
#5. Phát sinh mảng arr3 ngẫu nhiên 10 phần tử số nguyên từ 15-35
np.random.seed(3)
arr3=np.random.randint(15,36,size=(10,))
print(arr3)

[25 18 23 15 34 25 26 24 25 21]


In [ ]:
#6.  Liệt kê ra các phần tử giống nhau trong arr1 và arr3

In [ ]:
#7. Tạo mảng arr4 là mảng arr1 nhưng có 2 dòng, 5 cột 