In [2]:
import numpy as np

In [3]:
# Câu 1: Tạo array arr_zeros có 10 phần tử 0, cập nhật phần tử ở vị trí thứ 5 là 1
arr_zeros=np.zeros(10,)
arr_zeros[4]=1
print(arr_zeros)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
# Câu 2: Tạo và in array arr_h có giá trị từ 10 đến 24 
# In danh sách các phần tử theo tứ tự đảo ngược của arr_h vừa tạo
arr_h=np.arange(10,25)
print(arr_h[::-1])

[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [5]:
# Câu 3: Cho array arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]) 
# Tạo array arr_l từ arr_k với các phần tử khác 0
arr_k = np.array([1, 2, 0, 8, 2, 0, 1, 3, 0, 5, 0]) 
arr_l=arr_k[arr_k!=0]
print(arr_l)

[1 2 8 2 1 3 5]


In [7]:
# Câu 4: Từ array arr_l của câu 3, thêm 2 phần tử có giá trị là 10 và 20 vào cuố
arr_l=np.append(arr_l,[10,20])
print(arr_l)

[ 1  2  8  2  1  3  5 10 20]


In [8]:
# Câu 5: Từ array của câu 4, thêm phần tử có giá trị 100 vào vị trí có index 5
arr_l=np.insert(arr_l,5,100)
print(arr_l)

[  1   2   8   2   1 100   3   5  10  20]


In [9]:
# Câu 6: Từ array của câu 5, xóa các phần tử tại vị trí có index = 0,1,2
arr_l=np.delete(arr_l,[0,1,2])
print(arr_l)

[  2   1 100   3   5  10  20]
