In [1]:
import numpy as np

In [13]:
# Câu 1: Tạo numpy array có giá trị từ 0-9 và lưu vào biến arr
# Hiển thị các phần tử có trong arr
# Xem kiểu dữ liệu (type) của arr
# Xem kích thước (shape) của arr

a=np.arange(10)
print(a)
print(type(a))
print(a.shape)
print(a.size)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10


In [20]:
# Câu 2: Từ array arr ở câu 1 => tạo arr_odd và arr_even 
# Hiển thị các phần tử có trong arr_odd và arr_even
b=a[a%2==0]
print(f'arr_odd:\n{b}')
c=a[a%2!=0]
print(f'arr_odd:\n{c}')

arr_odd:
[0 2 4 6 8]
arr_odd:
[1 3 5 7 9]


In [22]:
# Câu 3: Từ array arr ở câu 1=> tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100
# Hiển thị các phần tử có trong arr_update_1
a[a%2!=0]=100
arr_update_1=a.copy()
print(arr_update_1)

[  0 100   2 100   4 100   6 100   8 100]
