In [1]:
# Tạo trang R trên colab: https://colab.research.google.com/notebook#create=true&language=r
a = 5
b = 7
c = a + b

In [2]:
fruit = c("a",'b','c')

In [3]:
print(fruit)

[1] "a" "b" "c"


In [4]:
print(c)

[1] 12


**Exercise 1: Tạo matrix**

In [5]:
x <- c(1, 2, 3)
y <- c(4, 5, 6)
z <- c(7, 8, 9)
v1 <- c(x, y, z)
matrix_1 <-matrix(v1, nrow = 3, ncol = 3, byrow = TRUE,
dimnames = list(c("r1", "r2", "r3"), c("c1", "c2", "c3")))

In [6]:
print("Matrix 1")
print(matrix_1)
t_matrix_1 <- t(matrix_1)
print("Ma tran chuyen vi cua matrix_1")
print(t_matrix_1)

[1] "Matrix 1"
   c1 c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9
[1] "Ma tran chuyen vi cua matrix_1"
   r1 r2 r3
c1  1  4  7
c2  2  5  8
c3  3  6  9


**Exercise 2: Tạo và tính toán trên matrix**

In [7]:
matrix_B <- matrix(data = c(1:12), nrow = 4,
dimnames = list(c("a", "b", "c", "d"), c("x", "y", "z")))
print("Matrix B:")
print(matrix_B)
tB <- t(matrix_B)
print("Transpose of Matrix B:")
print(tB)
subB<-matrix_B[2:dim(matrix_B)[1],1:3]
print("Sub of Matrix B:")
print(subB)

[1] "Matrix B:"
  x y  z
a 1 5  9
b 2 6 10
c 3 7 11
d 4 8 12
[1] "Transpose of Matrix B:"
  a  b  c  d
x 1  2  3  4
y 5  6  7  8
z 9 10 11 12
[1] "Sub of Matrix B:"
  x y  z
b 2 6 10
c 3 7 11
d 4 8 12


In [8]:
matrix_A <- matrix(data = c(1:9), nrow = 3,
dimnames = list(c("a", "b", "c"), c("x", "y", "z")))
print("Matrix A:")
print(matrix_A)
# 3A
A3 <- matrix_A * 3
print("3*A:")
print(A3)
A_plus_subB <- matrix_A + subB
print("A + sub B:")
print(A_plus_subB)
A_minus_subB <- matrix_A - subB
print("A - sub B:")
print(A_minus_subB)

[1] "Matrix A:"
  x y z
a 1 4 7
b 2 5 8
c 3 6 9
[1] "3*A:"
  x  y  z
a 3 12 21
b 6 15 24
c 9 18 27
[1] "A + sub B:"
  x  y  z
a 3 10 17
b 5 12 19
c 7 14 21
[1] "A - sub B:"
   x  y  z
a -1 -2 -3
b -1 -2 -3
c -1 -2 -3


**Exercise 3: Tạo và tính toán trên matrix**

In [9]:
n = as.integer(readline(prompt = "Nhap n: "))

Nhap n: 5


In [10]:
A1 <- matrix(runif(n*n, min = 1, max = n*n), n, n)
print("A1")
print(A1)

[1] "A1"
          [,1]      [,2]      [,3]      [,4]      [,5]
[1,] 24.833539 12.397392 10.554147 22.751132  3.700650
[2,]  9.462093  9.561501 19.916237 22.898271 24.342635
[3,] 11.937084  1.465527 16.788642 12.279766  8.273077
[4,]  9.896532 21.079367 21.645558  3.122598  7.588826
[5,] 21.476559 22.773353  2.056116 10.525180 21.370393


In [11]:
m = as.integer(readline(prompt = "Nhap m: "))

Nhap m: 8


In [13]:
A2 <- matrix(runif(n*m, min = 1, max = n*m), n, m)
print("A2")
print(A2)

[1] "A2"
         [,1]      [,2]      [,3]      [,4]      [,5]     [,6]      [,7]
[1,] 18.57571 10.529170 21.215739 35.425001 15.159079 26.42101 28.880861
[2,] 39.80503 14.593161  9.647127  7.334699 30.928164 22.13670 37.639606
[3,] 34.19632 22.747748 15.074168  9.026138  8.214711 35.30800 12.889008
[4,] 15.48413 36.110806 38.902150 16.057009  5.968519 29.42484 11.674695
[5,] 39.03091  8.137752 35.010349 18.660884 30.365558 22.83252  6.017122
          [,8]
[1,]  2.849421
[2,]  7.427521
[3,] 15.084155
[4,]  4.167601
[5,] 11.541812


In [14]:
M <- solve(A1, A2)
print("Matrix M")
print(M)

[1] "Matrix M"
           [,1]       [,2]       [,3]        [,4]        [,5]       [,6]
[1,]  1.8430176  0.7977001  1.2857710  0.59225928 -0.07931038  2.0468015
[2,] -1.3735047 -0.1159778  0.6363540  0.71408163  0.29549791 -0.9976522
[3,]  0.6990399  1.5422477  0.6963275 -0.03726164 -0.38684775  1.3797007
[4,] -1.0805887 -1.0736834 -1.1695115  0.67045292  0.62223200 -1.2607870
[5,]  1.9028489  0.0831418  0.1769780 -0.80957163  0.91648733  0.5628037
           [,7]       [,8]
[1,] -1.1231293  1.2479032
[2,]  0.7312879 -0.9959690
[3,]  0.1847541  0.4560132
[4,]  2.0778785 -1.0382412
[5,] -0.4101808  0.8148076


In [15]:
print("Row 1")
print(M[1,])

print("Column 1")
print(M[,1])

[1] "Row 1"
[1]  1.84301761  0.79770011  1.28577099  0.59225928 -0.07931038  2.04680146
[7] -1.12312931  1.24790319
[1] "Column 1"
[1]  1.8430176 -1.3735047  0.6990399 -1.0805887  1.9028489


In [16]:
if (n>=3 && m>=2){
print("M[3][2]")
print(M[3,2])
}

[1] "M[3][2]"
[1] 1.542248


**Exercise 4: Tạo và tính toán trên array**

In [17]:
matrix_1 <- matrix(c(1:9),nrow = 3, byrow = TRUE)
matrix_2 <- matrix(c(10:18),nrow = 3, byrow = TRUE)
A3 <- array(c(matrix_1, matrix_2), dim = c(3, 3, 2),
dimnames = list(c("r1", "r2", "r3"),
c("c1", "c2", "c3"),
c("matrix1", "matrix2")))
print("Array A3:")
print(A3)

[1] "Array A3:"
, , matrix1

   c1 c2 c3
r1  1  2  3
r2  4  5  6
r3  7  8  9

, , matrix2

   c1 c2 c3
r1 10 11 12
r2 13 14 15
r3 16 17 18



In [18]:
print("Tong theo dong cua tat ca matrix")
print(apply(A3, c(1),sum))
print("Tong theo cot cua tat ca matrix")
print(apply(A3, c(2),sum))
print("Tong theo matrix cua array")
print(apply(A3, c(3),sum))
print("Tong dong 1, matrix1")
print(sum(A3[1,,1]))
print("Tich cot 2, matrix2")
print(prod(A3[, 2,2]))

[1] "Tong theo dong cua tat ca matrix"
r1 r2 r3 
39 57 75 
[1] "Tong theo cot cua tat ca matrix"
c1 c2 c3 
51 57 63 
[1] "Tong theo matrix cua array"
matrix1 matrix2 
     45     126 
[1] "Tong dong 1, matrix1"
[1] 6
[1] "Tich cot 2, matrix2"
[1] 2618


**Exercise 5: Tạo và tính toán trên array**

In [19]:
v <- c()
i <-1
while(i<=50){
x = floor(runif(1, min = 5, max = 50))
if (x%%2==0){
v[i] <-x
i <- i + 1
}
}
print(v)

 [1] 44 38 18 10 10 10 28 38  6 48  6 44 32 48 36 44 32 36 32 46 48 20 46 14  6
[26] 22 46 36 46 46  6 40 36 48 34 10 26 46 10 36 46 46 26 22 18 38  6 26 16 10


In [38]:
A4 <- array(v, dim=c(5, 5, 2))
print("Array A4:")
print(A4)

[1] "Array A4:"
, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]   44   10    6   44   48
[2,]   38   28   44   32   20
[3,]   18   38   32   36   46
[4,]   10    6   48   32   14
[5,]   10   48   36   46    6

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]   22    6   10   46   38
[2,]   46   40   26   46    6
[3,]   36   36   46   26   26
[4,]   46   48   10   22   16
[5,]   46   34   36   18   10



In [39]:
rows <- nrow(A4)
print(rows)

[1] 5


In [40]:
cols <- ncol(A4)
print(cols)

[1] 5


In [41]:
dims <- dim(A4)[3]
print(dims)

[1] 2


In [42]:
i <- 1
j <- 1
k <- 1
tong <-0
while(i<=dims){
j <-1
while(j<=rows){
k <-1
while(k<=cols){
if(A4[j,k,i]%% 2 == 0 & A4[j,k,i]%% 3 == 0 & A4[j,k,i]%% 6 == 0){
print(paste("A4[", j,",", k,",", i,"] =", A4[j,k,i]))
tong <- tong + A4[j,k,i]
}
k <- k+1
}
j <- j+1
}
i <- i+1
}
print(paste("Tong =", tong))

[1] "A4[ 1 , 3 , 1 ] = 6"
[1] "A4[ 1 , 5 , 1 ] = 48"
[1] "A4[ 3 , 1 , 1 ] = 18"
[1] "A4[ 3 , 4 , 1 ] = 36"
[1] "A4[ 4 , 2 , 1 ] = 6"
[1] "A4[ 4 , 3 , 1 ] = 48"
[1] "A4[ 5 , 2 , 1 ] = 48"
[1] "A4[ 5 , 3 , 1 ] = 36"
[1] "A4[ 5 , 5 , 1 ] = 6"
[1] "A4[ 1 , 2 , 2 ] = 6"
[1] "A4[ 2 , 5 , 2 ] = 6"
[1] "A4[ 3 , 1 , 2 ] = 36"
[1] "A4[ 3 , 2 , 2 ] = 36"
[1] "A4[ 4 , 2 , 2 ] = 48"
[1] "A4[ 5 , 3 , 2 ] = 36"
[1] "A4[ 5 , 4 , 2 ] = 18"
[1] "Tong = 438"


**Exercise 6: Tạo và tính toán trên list**

In [43]:
p <- c(2,7,8)
q <- c("A", "B", "C")
x <- list(p, q)
print("List x:")
print(x)

[1] "List x:"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "B" "C"



In [44]:
print(paste("list[2]: ",toString(x[2])))
print(paste("vector[2] of list[2]:", x[[2]][2]))
x[[2]][2]<- "K"
print("List after changing")
print(x)

[1] "list[2]:  c(\"A\", \"B\", \"C\")"
[1] "vector[2] of list[2]: B"
[1] "List after changing"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "K" "C"



In [45]:
t<- c(1, 3, 4)
x <- c(x, list(t))
print("List after insert:")
print(x)


[1] "List after insert:"
[[1]]
[1] 2 7 8

[[2]]
[1] "A" "K" "C"

[[3]]
[1] 1 3 4



In [46]:
#cach 2
x[length(x)+1]<-list(t)
print(x)

[[1]]
[1] 2 7 8

[[2]]
[1] "A" "K" "C"

[[3]]
[1] 1 3 4

[[4]]
[1] 1 3 4



In [47]:
a <- list ("x"=5, "y"=10, "z"=15)
print("List a:")
print(a)

[1] "List a:"
$x
[1] 5

$y
[1] 10

$z
[1] 15



In [48]:
#tinh tong cua list
print(paste("Sum of list:", sum(unlist(a))))

[1] "Sum of list: 30"


In [49]:
Newlist <- list(a=1:10, b="Good morning", c="Hi")
print("Newlist:")
print(Newlist)


[1] "Newlist:"
$a
 [1]  1  2  3  4  5  6  7  8  9 10

$b
[1] "Good morning"

$c
[1] "Hi"



In [50]:
#cong them 1 vao cac phan tu cua element a trong list
Newlist$a <-Newlist$a+1
print(Newlist)

$a
 [1]  2  3  4  5  6  7  8  9 10 11

$b
[1] "Good morning"

$c
[1] "Hi"



**Exercise 7: Tạo và tính toán trên list**

In [51]:
year <- c(2008:2018)
month <- c(1:12)
day <- c(1:31)
# list
year_month_day.list <- list("year" = year, "month" = month, "day" = day)
print("List year_month_day:")
print(year_month_day.list)

[1] "List year_month_day:"
$year
 [1] 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [28]:
year_month_day.list$year <- c(2010:2020)
print("List year_month_day after changing:")
print(year_month_day.list)

[1] "List year_month_day after changing:"
$year
 [1] 2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [29]:
year_month_day.list$year <- year_month_day.list$year[-1]
print("After drop the first year in year:")
print(year_month_day.list)

[1] "After drop the first year in year:"
$year
 [1] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [52]:
x <- c(1,3,4,7,11,18,29)
cal.list <- list("x*2"= x*2,"x/2"=x/2, "sqrt(x)"=sqrt(x))
print("List calculator:")
print(cal.list)


[1] "List calculator:"
$`x*2`
[1]  2  6  8 14 22 36 58

$`x/2`
[1]  0.5  1.5  2.0  3.5  5.5  9.0 14.5

$`sqrt(x)`
[1] 1.000000 1.732051 2.000000 2.645751 3.316625 4.242641 5.385165



In [53]:
#tra ve cac phan tu 3-5 $sqrt(x)
print("3 phan tu giua")
print(cal.list$`sqrt(x)`[3:5])

[1] "3 phan tu giua"
[1] 2.000000 2.645751 3.316625


In [54]:
#tao 1 list moi co 2 list tren
year_month_day_cal.list <- c(year_month_day.list, cal.list)
print("year_month_day_cal.list: ")
print(year_month_day_cal.list)

[1] "year_month_day_cal.list: "
$year
 [1] 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017 2018

$month
 [1]  1  2  3  4  5  6  7  8  9 10 11 12

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31

$`x*2`
[1]  2  6  8 14 22 36 58

$`x/2`
[1]  0.5  1.5  2.0  3.5  5.5  9.0 14.5

$`sqrt(x)`
[1] 1.000000 1.732051 2.000000 2.645751 3.316625 4.242641 5.385165



In [32]:
# tao mot list con chua year, x*2 va day tu list moi tao ra tren
year_x2_day <- year_month_day_cal.list[c("year", "x*2", "day")]
print("list year_x2_day:")
print(year_x2_day)

[1] "list year_x2_day:"
$year
 [1] 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020

$`x*2`
[1]  2  6  8 14 22 36 58

$day
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
[26] 26 27 28 29 30 31



In [33]:
# chieu dai cua x*2
print(paste("length of x*2:", length(year_x2_day$`x*2`)))
print(paste("last value of year:",
year_x2_day$year[length(year_x2_day$year)]))

[1] "length of x*2: 7"
[1] "last value of year: 2020"


**Exercise 8: Tạo và tính toán trên list**

In [55]:
# cho list
y <- list(c("a", "b", "c"), c(1,2,3),10)


In [56]:
names(y) <- c("one", "two", "three")
print("List y:")
print(y)

[1] "List y:"
$one
[1] "a" "b" "c"

$two
[1] 1 2 3

$three
[1] 10



In [57]:
print(paste("Length of one, two, three are:",length(y$one), ",",length(y$two), ",",length(y$three)))

[1] "Length of one, two, three are: 3 , 3 , 1"


In [58]:
z <- list(c("a", "b", "c"), c(1,3,5,7),TRUE)
print("list z:")
print(z)

[1] "list z:"
[[1]]
[1] "a" "b" "c"

[[2]]
[1] 1 3 5 7

[[3]]
[1] TRUE



In [59]:
# in y not in z
t <- setdiff(y, z)
print("in y not in z:")
print(t)

[1] "in y not in z:"
$two
[1] 1 2 3

$three
[1] 10



In [60]:
#in z not in y
f <- setdiff(z, y)
print("in z not in y")
print(f)

[1] "in z not in y"
[[1]]
[1] 1 3 5 7

[[2]]
[1] TRUE

