In [3]:
"""=============================================================================
Ex2: EIGENDECOMPOSITION
    Câu 1:
        a) Tạo ma trận A(5 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
        b) Phân tích eigenvalues và eigenvectors
        c) Kiểm tra eigenvector đầu tiên theo dot và theo eigenvalue có bằng nhau?
           Nếu bằng nhau thì tái tạo A từ các eigenvalues và eigenvectors
============================================================================="""
    
import numpy  as np
import random       

from numpy.linalg import eig, inv
from numpy import diag

##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end + 1)
            
            # Thêm giá trị vào dòng hiện hành 
            row.append(a)
            
        # Thêm dòng vào ma trận    
        mtr.append(row)
        
    return np.array(mtr)
##------------------------------------------------------------------------------
    
## a) Tạo ma trận A(5 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10

## Test cases
m, n, min, max = 5, 5, 1, 10
A1 = create_matrix_random(m, n, min, max)

A2 = np.array([[10,  8, 11,  9,  6],
               [ 3,  9,  3,  8,  4], 
               [ 3,  7,  7, 11,  2], 
               [ 9,  2, 11, 10, 11], 
               [11,  6, 10,  2,  7]])

A3 = np.array([[ 8,  5,  4, 11,  8],
               [ 3,  9, 10,  8,  8],
               [ 1,  7,  6,  4, 10],
               [ 5,  1,  9,  8, 11],
               [ 8,  9,  3,  2,  9]])

A = A3
print('Ma trận A', A.shape, ':\n', A)

## b) Phân tích eigenvalues và eigenvectors
values, vectors = eig(A)

for j in range(len(values)):
    eigenvalue = values[j] 
    # print(type(eigenvalue))

    r = values[j].real
    i = values[j].imag
    print('Eigenvalue[%d]' %j, '= (%f,' %r, '%f)' %i)
    
print('\nEigenvectors', vectors.shape, ':\n', vectors)

## c) Kiểm tra eigenvector đầu tiên theo dot và theo eigenvalue có bằng nhau?
##    Nếu bằng nhau thì tái tạo A từ các eigenvalues và eigenvectors
B = A.dot(vectors[:, 0])
print('\nVectơ B:\n', B.astype(int))

C = vectors[:, 0] * values[0]
print('\nVectơ C:\n', C.astype(int))

Q = vectors
L = diag(values)

print('\nTái tạo ma trận A:\n', Q.dot(L).dot(inv(Q)).astype(int))


Ma trận A (5, 5) :
 [[ 8  5  4 11  8]
 [ 3  9 10  8  8]
 [ 1  7  6  4 10]
 [ 5  1  9  8 11]
 [ 8  9  3  2  9]]
Eigenvalue[0] = (33.146995, 0.000000)
Eigenvalue[1] = (7.612985, 0.000000)
Eigenvalue[2] = (0.981858, 6.634282)
Eigenvalue[3] = (0.981858, -6.634282)
Eigenvalue[4] = (-2.723695, 0.000000)

Eigenvectors (5, 5) :
 [[-0.48635944+0.j          0.65694934+0.j         -0.12754405+0.35389539j
  -0.12754405-0.35389539j -0.52335   +0.j        ]
 [-0.5008194 +0.j         -0.51712648+0.j         -0.30208186+0.2796311j
  -0.30208186-0.2796311j   0.16229336+0.j        ]
 [-0.3698279 +0.j         -0.44804743+0.j         -0.05236767-0.26362682j
  -0.05236767+0.26362682j -0.63829232+0.j        ]
 [-0.43704785+0.j          0.29889472+0.j         -0.40204406-0.33395451j
  -0.40204406+0.33395451j  0.4345509 +0.j        ]
 [-0.42994293+0.j          0.10446634+0.j          0.58620564+0.j
   0.58620564-0.j          0.32173603+0.j        ]]

Vectơ B:
 [-16 -16 -12 -14 -14]

Vectơ C:
 [-16 -16 -12 -14

<ipython-input-3-4fc49ad81825>:72: ComplexWarning: Casting complex values to real discards the imaginary part
  print('\nVectơ B:\n', B.astype(int))
<ipython-input-3-4fc49ad81825>:75: ComplexWarning: Casting complex values to real discards the imaginary part
  print('\nVectơ C:\n', C.astype(int))
<ipython-input-3-4fc49ad81825>:80: ComplexWarning: Casting complex values to real discards the imaginary part
  print('\nTái tạo ma trận A:\n', Q.dot(L).dot(inv(Q)).astype(int))


In [41]:
"""=============================================================================
Ex2: EIGENDECOMPOSITION
    Câu 2:
        a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 9
        b) Tạo ma trận đối xứng B = A.A_T
        c) Phân tích eigenvalues và eigenvectors của B
============================================================================="""

import numpy as np
from numpy.linalg import eig

## a) Tạo ma trận A(5 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
m, n, min, max = 4, 4, 1, 9
A = np.random.randint(1, 10, (n, n))
print('Ma trận A', A.shape, ':\n', A)

## b) Tạo ma trận đối xứng B = A.A_T
B = A @ A.T
print('\nMa trận đối xứng B', B.shape, ':\n', B)

## c) Phân tích eigenvalues và eigenvectors
values, vectors = eig(B)
print('\nSố lượng giá trị riêng: %d' %len(values))
print('\nEigenvalues',  values.shape,  ':\n', values)
print('\nEigenvectors', vectors.shape, ':\n', vectors)



Ma trận A (4, 4) :
 [[5 4 1 7]
 [7 3 2 2]
 [4 9 6 1]
 [3 6 7 2]]

Ma trận đối xứng B (4, 4) :
 [[ 91  63  69  60]
 [ 63  66  69  57]
 [ 69  69 134 110]
 [ 60  57 110  98]]

Số lượng giá trị riêng: 4

Eigenvalues (4,) :
 [319.67323907  51.90716821  13.17885697   4.24073575]

Eigenvectors (4, 4) :
 [[-0.43273136 -0.72788897 -0.52224245 -0.100916  ]
 [-0.39359473 -0.37823816  0.82436246  0.1498186 ]
 [-0.61815717  0.43983163  0.0249771  -0.65100383]
 [-0.52507949  0.3655977  -0.21694584  0.73726817]]
