In [ ]:
# Tạo trang R trên colab: https://colab.research.google.com/notebook#create=true&language=r
a <- 5
b <- 7
c <- a + b

In [ ]:
fruit <- c("a",'b','c')

In [ ]:
print(fruit)

[1] "a" "b" "c"


In [ ]:
print(c)

[1] 12


In [ ]:
pass<- TRUE

In [ ]:
print(class(pass))

[1] "logical"


In [ ]:
name<- "Phuong"

In [ ]:
print(class(name))

[1] "character"


In [ ]:
age <- 15

In [ ]:
print(class(age))

[1] "numeric"


In [ ]:
mark <- 8.75

In [ ]:
print(class(mark))

[1] "numeric"


In [ ]:
int<-2L
print(class(int))

[1] "integer"


In [ ]:
fruit <-c('apple','pear')

In [ ]:
mix_vec<-c(1,TRUE,"ACB", 12.5)

In [ ]:
print(class(mix_vec))

[1] "character"


In [ ]:
mix_vec_1<-c(1,TRUE, 12.5)
print(class(mix_vec_1))

[1] "numeric"


In [ ]:
apple_colours <- c('green', 'green','yellow', 'red','red', 'red', 'green','white')

In [ ]:
factor_apple<-factor(apple_colours)

In [ ]:
print(factor_apple)

[1] green  green  yellow red    red    red    green  white 
Levels: green red white yellow


In [ ]:
print(nlevels(factor_apple))

[1] 4


In [ ]:
list1<-list(c(2,5,3),21.3,'spring')

In [ ]:
print(list1)

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
[1] "spring"



In [ ]:
M=matrix(c(1,2,3,4,5,6,7,8), nrow=2, ncol=4,byrow=TRUE)

In [ ]:
print(M)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8


In [ ]:
M1=matrix(c(1,2,3,4,5,6,7,8), ncol=3,byrow=TRUE)
print(M1)

Warning message in matrix(c(1, 2, 3, 4, 5, 6, 7, 8), ncol = 3, byrow = TRUE):
“data length [8] is not a sub-multiple or multiple of the number of rows [3]”


     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    1


In [ ]:
a=array(c('red', 'green','yellow'), dim=c(3,3,2))
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "red"    "red"    "red"   
[2,] "green"  "green"  "green" 
[3,] "yellow" "yellow" "yellow"

, , 2

     [,1]     [,2]     [,3]    
[1,] "red"    "red"    "red"   
[2,] "green"  "green"  "green" 
[3,] "yellow" "yellow" "yellow"



In [ ]:
BMI =data.frame(
  gender=c("Male", "Male", "Female"),
  height=c(152,171.5,165),
  weight=c(81,93,78),
  age=c(42,38,26)
)
print(BMI)

  gender height weight age
1   Male  152.0     81  42
2   Male  171.5     93  38
3 Female  165.0     78  26


In [ ]:
colors<-c("red","green","blue")
print(colors)

[1] "red"   "green" "blue" 


In [ ]:
numbers=c(10,15.5,7)
print(numbers)

[1] 10.0 15.5  7.0


In [ ]:
c(TRUE,FALSE,TRUE,TRUE) ->pass
print(pass)

[1]  TRUE FALSE  TRUE  TRUE


In [ ]:
?reversed


In [ ]:
print(ls())

 [1] "a"             "age"           "apple_colours" "b"            
 [5] "BMI"           "c"             "colors"        "factor_apple" 
 [9] "fruit"         "int"           "list1"         "M"            
[13] "M1"            "mark"          "mix_vec"       "mix_vec_1"    
[17] "name"          "numbers"       "pass"         


In [ ]:
v=c(2,5.5,6)
t=c(8,3,4)
print(v+t)

[1] 10.0  8.5 10.0


In [ ]:
print(v-t)

[1] -6.0  2.5  2.0


In [ ]:
print(v*t)

[1] 16.0 16.5 24.0


In [ ]:
print(v/t)

[1] 0.250000 1.833333 1.500000


In [ ]:
print(v%%t)

[1] 2.0 2.5 2.0


In [ ]:
print(v%/%t)

[1] 0 1 1


In [ ]:
print(v^t)

[1]  256.000  166.375 1296.000


In [ ]:
v=c(2,5.5,6,7)
t=c(8,3,4,7)

In [ ]:
print(v>t)

[1] FALSE  TRUE  TRUE FALSE


In [ ]:
print(v<t)

[1]  TRUE FALSE FALSE FALSE


In [ ]:
print(v==t)

[1] FALSE FALSE FALSE  TRUE


In [ ]:
print(v>=t)

[1] FALSE  TRUE  TRUE  TRUE


In [ ]:
print(v<=t)

[1]  TRUE FALSE FALSE  TRUE


In [ ]:
print(v!=t)

[1]  TRUE  TRUE  TRUE FALSE


In [ ]:
v=c(3,1,TRUE,0)
t=c(4,1,FALSE,2)

In [ ]:
print(v&t)

[1]  TRUE  TRUE FALSE FALSE


In [ ]:
print(v|t)

[1] TRUE TRUE TRUE TRUE


In [ ]:
print(!v)

[1] FALSE FALSE FALSE  TRUE


In [ ]:
print(!t)

[1] FALSE FALSE  TRUE FALSE


In [ ]:
v=c(FALSE,1,TRUE,0)

In [ ]:
t=c(4,1,FALSE,2)

In [ ]:
print(v&&t)

[1] FALSE


In [ ]:
print(v||t)

[1] TRUE


In [ ]:
v= 1:10
print(v)

 [1]  1  2  3  4  5  6  7  8  9 10


In [ ]:
v1=8
v2=12
v=c(2,4,3,8,9,11)

In [ ]:
print(v1 %in% v)

[1] TRUE


In [ ]:
print(v2 %in% v)

[1] FALSE


In [ ]:
M=matrix(c(1,1,1,2,2,2), nrow=2,ncol=3,byrow=TRUE)

In [ ]:
print(t(M))

     [,1] [,2]
[1,]    1    2
[2,]    1    2
[3,]    1    2


In [ ]:
T=M %*% t(M)

In [ ]:
print(T)

     [,1] [,2]
[1,]    3    6
[2,]    6   12


In [ ]:
name =readline(prompt="Enter name: ")

Enter name: Giang


In [ ]:
age =readline(prompt="Enter age: ")

Enter age: 29


In [ ]:
age = as.integer(age)

In [ ]:
print(paste(name, age))

[1] "Giang 29"


In [ ]:
print(name)

[1] "Giang"


In [ ]:
print(age)

[1] 29


In [ ]:
print(paste("Hi", name, "next year you will be", age+1, "year old"))

[1] "Hi Giang next year you will be 30 year old"


In [ ]:
colors =c("red","green","blue")
cat("color are",colors, "\n")


color are red green blue 


In [ ]:
s1="This is first sentence."
s2='This is second sentence.'
s3="This is 'third' sentence"
s4='This is "forth" sentence'
print(s1)
print(s2)
print(s3)
print(s4)

[1] "This is first sentence."
[1] "This is second sentence."
[1] "This is 'third' sentence"
[1] "This is \"forth\" sentence"


In [ ]:
a="one"
b='two'
c="three"

In [ ]:
print(paste(a,b,c))

[1] "one two three"


In [ ]:
print(paste(a,b,c, sep="-"))

[1] "one-two-three"


In [ ]:
print(paste(a,b,c, sep=""))

[1] "onetwothree"


In [ ]:
print(nchar(s1))

[1] 23


In [ ]:
print(toupper(s1))

[1] "THIS IS FIRST SENTENCE."


In [ ]:
print(tolower(s1))

[1] "this is first sentence."


In [ ]:
s_sub=substring(s1, 5,14)

In [ ]:
print(s_sub)

[1] " is first "


In [ ]:
print(chartr(" ", "-", s1))

[1] "This-is-first-sentence."


In [ ]:
character_list=strsplit(s1, " ")

In [ ]:
word_list=unlist(character_list)

In [ ]:
print(word_list)

[1] "This"      "is"        "first"     "sentence."


In [ ]:
sorted_list=sort(word_list)

In [ ]:
print(sorted_list)

[1] "first"     "is"        "sentence." "This"     


In [ ]:
sorted_list_1=sort(word_list, decreasing=TRUE)

In [ ]:
print(sorted_list_1)

[1] "This"      "sentence." "is"        "first"    


In [ ]:
print(date())

[1] "Fri Apr  1 12:51:04 2022"


In [ ]:
print(Sys.Date())

[1] "2022-04-01"


In [ ]:
print(as.Date("1/4/2022",format("%d/%m/%Y")))

[1] "2022-04-01"


In [ ]:
print(format(Sys.Date(), format="%B %d %Y"))

[1] "April 01 2022"


In [ ]:
print(format(Sys.Date(), format="%d %m %Y"))

[1] "01 04 2022"


In [ ]:
distance=Sys.Date()-as.Date("2022-03-01")
print(distance)
print(as.numeric(distance))

Time difference of 31 days
[1] 31


In [ ]:
distance_1=difftime(Sys.Date(), as.Date("1993-07-11"), units="weeks")
print(as.numeric(distance_1))

[1] 1498.714


In [ ]:
print(distance_1)

Time difference of 1498.714 weeks
